---
name: Request Reviewers
on:
  pull_request:
    types:
      - opened
jobs:
  request-reviewers:
    runs-on: ubuntu-latest
    steps:
      -name: Request Reviewers
      uses: actions/github-script@v6
      with:
        script: >
          const reviewers ["reviewer1", "reviewer2"];

          const team_reviewers = ["team1"];

          github.pulls.requestReviewers({
           owner: context.repo.owner,
           repo: context.repo.repo,
           pull_number: context.payload.pull_request.number, reviewers: reviewers,
           team_reviewers: team_reviewers });
